minor readme update
cancelei/blog-in-rails pull request #6
Opened 2023-10-11 01:19 UTC by cancelei

t

2023-10-12 02:56 UTC, Davidosky007 requested changes
Hi @cancelei 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* All views setup properly 👍 
* Well-written PR 👍 
* No linter errors 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 02:56 UTC, Davidosky007 commented on app/views/users/show.html.erb
> +    <% @user.posts.each do |post| %>
* According to the wireframe you are to have a method that returns 3 most recent posts of the user so in your user show view file you will render the posts like this `<% @user.recent_post.each do |post| %>` 
![image](https://github.com/cancelei/blog-in-rails/assets/52497246/8bb65613-8975-4cae-830a-35f1554b7ec6)

2023-10-12 02:56 UTC, Davidosky007 commented on app/views/posts/index.html.erb
> +        <% post.comments.each do |comment| %>
* Also here According to the wireframe you are to have a method that returns 5 most recent posts of the user so in your post index view file you will render the comments like this ``<% post.recent_comments.each do |comment| %>`` 
![image](https://github.com/cancelei/blog-in-rails/assets/52497246/d635a73d-5d23-4a5a-a7d8-32a3ca66dc6b)

2023-10-13 14:33 UTC, shella12 requested changes
Hi @cancelei, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Added required view files ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 14:33 UTC, shella12 commented on app/views/users/show.html.erb
> +    <% end %>
- [ ] As mentioned by the previous reviewer when we are visiting `users/:id` page there should be 3 most recent posts by the user on display and you can easily do that by making use of the method in your user model `recent_posts`. Example snippet:

```rb

# app/views/users/show.html.erb

[...]

<% @user.recent_post.each do |post| %>

<h4><%= link_to post.title, user_post_path(post) %></h4>
<p><%= post.text %></p>
<p>
<small>Comments: <%= post.comments_counter || 0 %>,</small> 
<small>Likes: <%= post.likes_counter || 0 %></small>
</p>

<% end %>

<button>
<%= link_to 'See all Post', user_posts_path(@user) %>
</button>


```

WireFrame| your App
--|--
<img width="445" alt="Screenshot 2023-10-13 at 7 29 37 PM" src="https://github.com/cancelei/blog-in-rails/assets/44798044/18d36a77-49d1-4938-bc64-582b1f7a0f0b">|<img width="779" alt="Screenshot 2023-10-13 at 7 19 23 PM" src="https://github.com/cancelei/blog-in-rails/assets/44798044/46f0b75a-c7ea-495d-84b1-4c06e2b281e9">

2023-10-13 14:33 UTC, shella12 commented on app/views/posts/index.html.erb
> +        <% end %>
- [ ] As mentioned by the previous reviewer please show the five most recent comments under the relevant post when we are on `users/:id/posts` page and you can easily do that by making use of the methods in your post model `recent_comments`. Example snippet: 

```rb
 <% post.recent_comments.each do |comment| %>
  <p><%= comment.author.name %>: <%= comment.text %></p> 
 <% end %>

```

WireFrame| your App
--|--
<img width="449" alt="Screenshot 2023-10-13 at 7 29 50 PM" src="https://github.com/cancelei/blog-in-rails/assets/44798044/b69632ff-1826-4555-b933-fe0a7160ca03">|<img width="575" alt="Screenshot 2023-10-13 at 7 30 46 PM" src="https://github.com/cancelei/blog-in-rails/assets/44798044/8045e80a-8a0f-4cd7-9ef8-98ac88995af1">

2023-10-13 15:57 UTC, cynthiainga approved these changes
Hi @cancelei, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [x] All requested changes are made ✔️ 
- [x] Correct Gitflow ✔️ 
- [x] No linters errors ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 19:06 UTC, merged